// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//protoc --go_out=plugins=grpc:. order.proto
type BookingGoodsRequest struct {
	GoodsId              int32    `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingGoodsRequest) Reset()         { *m = BookingGoodsRequest{} }
func (m *BookingGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*BookingGoodsRequest) ProtoMessage()    {}
func (*BookingGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *BookingGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingGoodsRequest.Unmarshal(m, b)
}
func (m *BookingGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingGoodsRequest.Marshal(b, m, deterministic)
}
func (m *BookingGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingGoodsRequest.Merge(m, src)
}
func (m *BookingGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_BookingGoodsRequest.Size(m)
}
func (m *BookingGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingGoodsRequest proto.InternalMessageInfo

func (m *BookingGoodsRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *BookingGoodsRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BookingGoodsRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *BookingGoodsRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BookingGoodsResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingGoodsResponse) Reset()         { *m = BookingGoodsResponse{} }
func (m *BookingGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*BookingGoodsResponse) ProtoMessage()    {}
func (*BookingGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *BookingGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingGoodsResponse.Unmarshal(m, b)
}
func (m *BookingGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingGoodsResponse.Marshal(b, m, deterministic)
}
func (m *BookingGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingGoodsResponse.Merge(m, src)
}
func (m *BookingGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_BookingGoodsResponse.Size(m)
}
func (m *BookingGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingGoodsResponse proto.InternalMessageInfo

func (m *BookingGoodsResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *BookingGoodsResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type FindByOrderIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByOrderIdRequest) Reset()         { *m = FindByOrderIdRequest{} }
func (m *FindByOrderIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByOrderIdRequest) ProtoMessage()    {}
func (*FindByOrderIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *FindByOrderIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOrderIdRequest.Unmarshal(m, b)
}
func (m *FindByOrderIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOrderIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByOrderIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOrderIdRequest.Merge(m, src)
}
func (m *FindByOrderIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByOrderIdRequest.Size(m)
}
func (m *FindByOrderIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOrderIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOrderIdRequest proto.InternalMessageInfo

func (m *FindByOrderIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindByOrderIdResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsId              int32    `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,3,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByOrderIdResponse) Reset()         { *m = FindByOrderIdResponse{} }
func (m *FindByOrderIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindByOrderIdResponse) ProtoMessage()    {}
func (*FindByOrderIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *FindByOrderIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOrderIdResponse.Unmarshal(m, b)
}
func (m *FindByOrderIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOrderIdResponse.Marshal(b, m, deterministic)
}
func (m *FindByOrderIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOrderIdResponse.Merge(m, src)
}
func (m *FindByOrderIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindByOrderIdResponse.Size(m)
}
func (m *FindByOrderIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOrderIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOrderIdResponse proto.InternalMessageInfo

func (m *FindByOrderIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindByOrderIdResponse) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *FindByOrderIdResponse) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *FindByOrderIdResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *FindByOrderIdResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindByOrderIdResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BookingGoodsRequest)(nil), "BookingGoodsRequest")
	proto.RegisterType((*BookingGoodsResponse)(nil), "BookingGoodsResponse")
	proto.RegisterType((*FindByOrderIdRequest)(nil), "FindByOrderIdRequest")
	proto.RegisterType((*FindByOrderIdResponse)(nil), "FindByOrderIdResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4e, 0xb4, 0x30,
	0x14, 0xc5, 0x03, 0x0c, 0x7c, 0x1f, 0xd7, 0x3f, 0x31, 0x15, 0x26, 0xcd, 0xc4, 0x18, 0xc3, 0xc2,
	0xb8, 0xea, 0x42, 0x97, 0x26, 0x2e, 0x66, 0xa1, 0x99, 0x8d, 0x9a, 0xc6, 0x17, 0x18, 0x69, 0x33,
	0x69, 0x0c, 0x5c, 0x6c, 0x61, 0xe1, 0x13, 0xf8, 0x2c, 0xbe, 0xa5, 0xa1, 0xd0, 0x08, 0xa4, 0xbb,
	0x7b, 0x4e, 0x2e, 0x9c, 0x7b, 0x7e, 0x00, 0x47, 0xa8, 0x85, 0xd4, 0xac, 0xd1, 0xd8, 0x62, 0x81,
	0x70, 0xbe, 0x45, 0xfc, 0x50, 0xf5, 0xe1, 0x09, 0x51, 0x18, 0x2e, 0x3f, 0x3b, 0x69, 0x5a, 0x42,
	0xe1, 0xdf, 0xa1, 0xd7, 0x3b, 0x41, 0x83, 0xab, 0xe0, 0x26, 0xe6, 0x4e, 0x92, 0x0c, 0xe2, 0x46,
	0xab, 0x52, 0xd2, 0xd0, 0xfa, 0x83, 0x20, 0x67, 0x10, 0xd5, 0x5d, 0x45, 0x23, 0xeb, 0xf5, 0x23,
	0x59, 0x43, 0xd2, 0x19, 0xa9, 0x77, 0x82, 0xae, 0xac, 0x39, 0xaa, 0xe2, 0x15, 0xb2, 0x79, 0xa0,
	0x69, 0xb0, 0x36, 0xb2, 0x4f, 0xb4, 0x77, 0x8d, 0x89, 0x29, 0x77, 0x92, 0x5c, 0x02, 0x94, 0x5a,
	0xee, 0x5b, 0xf9, 0xa6, 0xaa, 0x21, 0x36, 0xe2, 0x13, 0xa7, 0xb8, 0x86, 0xec, 0x51, 0xd5, 0x62,
	0xfb, 0xf5, 0x32, 0x3c, 0xe0, 0x3a, 0x9c, 0x42, 0xa8, 0xdc, 0xcb, 0x42, 0x25, 0x8a, 0x9f, 0x00,
	0xf2, 0xc5, 0xe2, 0x98, 0xbd, 0xd8, 0x9c, 0xb6, 0x0f, 0xe7, 0xed, 0x2f, 0x20, 0xb5, 0xe3, 0xf3,
	0xbe, 0x92, 0xb6, 0x6d, 0xca, 0xff, 0x0c, 0x47, 0x61, 0xe5, 0xa3, 0x10, 0x4f, 0x29, 0x2c, 0x3a,
	0x25, 0xcb, 0x4e, 0xb7, 0xdf, 0x01, 0xfc, 0xb7, 0x57, 0xf2, 0xa6, 0x24, 0xf7, 0x70, 0x3c, 0x45,
	0x46, 0x32, 0xe6, 0xf9, 0x64, 0x9b, 0x9c, 0x79, 0xb9, 0x3e, 0xc0, 0xc9, 0xac, 0x34, 0xc9, 0x99,
	0x8f, 0xd6, 0x66, 0xcd, 0xbc, 0x6c, 0xde, 0x13, 0xfb, 0x9f, 0xdc, 0xfd, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x9b, 0xfb, 0x31, 0x26, 0x36, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderRpcClient is the client API for OrderRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderRpcClient interface {
	BookingGoods(ctx context.Context, in *BookingGoodsRequest, opts ...grpc.CallOption) (*BookingGoodsResponse, error)
	FindByOrderId(ctx context.Context, in *FindByOrderIdRequest, opts ...grpc.CallOption) (*FindByOrderIdResponse, error)
}

type orderRpcClient struct {
	cc *grpc.ClientConn
}

func NewOrderRpcClient(cc *grpc.ClientConn) OrderRpcClient {
	return &orderRpcClient{cc}
}

func (c *orderRpcClient) BookingGoods(ctx context.Context, in *BookingGoodsRequest, opts ...grpc.CallOption) (*BookingGoodsResponse, error) {
	out := new(BookingGoodsResponse)
	err := c.cc.Invoke(ctx, "/OrderRpc/BookingGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) FindByOrderId(ctx context.Context, in *FindByOrderIdRequest, opts ...grpc.CallOption) (*FindByOrderIdResponse, error) {
	out := new(FindByOrderIdResponse)
	err := c.cc.Invoke(ctx, "/OrderRpc/FindByOrderId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderRpcServer is the server API for OrderRpc service.
type OrderRpcServer interface {
	BookingGoods(context.Context, *BookingGoodsRequest) (*BookingGoodsResponse, error)
	FindByOrderId(context.Context, *FindByOrderIdRequest) (*FindByOrderIdResponse, error)
}

// UnimplementedOrderRpcServer can be embedded to have forward compatible implementations.
type UnimplementedOrderRpcServer struct {
}

func (*UnimplementedOrderRpcServer) BookingGoods(ctx context.Context, req *BookingGoodsRequest) (*BookingGoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookingGoods not implemented")
}
func (*UnimplementedOrderRpcServer) FindByOrderId(ctx context.Context, req *FindByOrderIdRequest) (*FindByOrderIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByOrderId not implemented")
}

func RegisterOrderRpcServer(s *grpc.Server, srv OrderRpcServer) {
	s.RegisterService(&_OrderRpc_serviceDesc, srv)
}

func _OrderRpc_BookingGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).BookingGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderRpc/BookingGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).BookingGoods(ctx, req.(*BookingGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_FindByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).FindByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderRpc/FindByOrderId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).FindByOrderId(ctx, req.(*FindByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderRpc",
	HandlerType: (*OrderRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookingGoods",
			Handler:    _OrderRpc_BookingGoods_Handler,
		},
		{
			MethodName: "FindByOrderId",
			Handler:    _OrderRpc_FindByOrderId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
